/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#ab3500',
        'on-primary': '#ffffff',
        'primary-container': '#ff6b35',
        'on-primary-container': '#5f1900',
        'inverse-primary': '#ffb59d',
        'primary-fixed': '#ffdbd0',
        'primary-fixed-dim': '#ffb59d',
        'on-primary-fixed': '#390c00',
        'on-primary-fixed-variant': '#832600',
        secondary: '#5a5d70',
        'on-secondary': '#ffffff',
        'secondary-container': '#dee1f8',
        'on-secondary-container': '#606376',
        'secondary-fixed': '#dee1f8',
        'secondary-fixed-dim': '#c2c5db',
        'on-secondary-fixed': '#171b2b',
        'on-secondary-fixed-variant': '#424658',
        tertiary: '#00677e',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00a7cb',
        'on-tertiary-container': '#003744',
        'tertiary-fixed': '#b5ebff',
        'tertiary-fixed-dim': '#59d5fb',
        'on-tertiary-fixed': '#001f28',
        'on-tertiary-fixed-variant': '#004e60',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fff8f6',
        'on-background': '#261814',
        surface: '#fff8f6',
        'surface-dim': '#eed5cd',
        'surface-bright': '#fff8f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff1ed',
        'surface-container': '#ffe9e3',
        'surface-container-high': '#fde3db',
        'surface-container-highest': '#f7ddd5',
        'on-surface': '#261814',
        'on-surface-variant': '#594139',
        'inverse-surface': '#3c2d28',
        'inverse-on-surface': '#ffede8',
        outline: '#8d7168',
        'outline-variant': '#e1bfb5',
        'surface-tint': '#ab3500',
        'surface-variant': '#f7ddd5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        gutter: '16px',
        margin: '20px',
      },
      fontFamily: {
        inter: ['Inter', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-sm': ['Inter', 'system-ui', 'sans-serif'],
        h1: ['Inter', 'system-ui', 'sans-serif'],
        h2: ['Inter', 'system-ui', 'sans-serif'],
        h3: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        h1: ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
